config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'movies#index'
  resources :movies, only: :index do
    resource :watched_movies, only: [:create, :destroy]
  end
  resources :aws_texts
  resources :talks, only: :index
  resources :writing, only: :index
  resources :questions, only: [:index, :create, :show] do
  resources :solutions, only: [:create]
  end
  resources :phps, only: :index
  resources :monies, only: :index
  resources :marketings, only: :index
  resources :live_cordings
  resources :lines, only: [:index, :show]
  resources :edit_movies, only: :index
  resources :texts, only: [:index, :show] do
    resource :watched_texts, only: [:create, :destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord

  validates :title, presence: true
  validates :content, presence: true

end

app/models/edit_movie.rb
class EditMovie < ApplicationRecord
  validates :title,  presence: true
  validates :url,  presence: true 
end

app/models/line.rb
class Line < ApplicationRecord
end

app/models/live_cording.rb
class LiveCording < ApplicationRecord
end

app/models/marketing.rb
class Marketing < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true
end

app/models/money.rb
class Money < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watched_movies, dependent: :destroy
  validates :url, presence: true
  validates :title, presence: true
end

app/models/php.rb
class Php < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true
  validates :detail, presence: true
  has_many :solutions
end

app/models/solution.rb
class Solution < ApplicationRecord
    validates :detail, presence: true
    belongs_to :question
end

app/models/talk.rb
class Talk < ApplicationRecord
    validates :title, presence: true
    validates :url, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :watched_texts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :watched_movies, dependent: :destroy
  has_many :watched_texts, dependent: :destroy

end

app/models/watched_movie.rb
class WatchedMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, presence: true, uniqueness: { scope: :movie_id }
  validates :movie_id, presence: true
end

app/models/watched_text.rb
class WatchedText < ApplicationRecord
    belongs_to :user
    belongs_to :text
    validates :user_id, presence: true, uniqueness: { scope: :text_id }
    validates :text_id, presence: true
end

app/models/writing.rb
class Writing < ApplicationRecord
    validates :title, presence: true
    validates :url, presence: true
end

app/controllers/phps_controller.rb
class PhpsController < ApplicationController
  def index
    @phps = Php.all
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    @texts = Text.all
    @watched_texts_id = current_user.watched_texts.pluck(:text_id)
  end

  def show
    @text = Text.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  def nav_color
    controller_name == "lines" ? "#28a745" : "#5C99FF"
  end


    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0] if language.present?

            case language.to_s
            when 'rb'
                lang = :ruby
            when 'yml'
                lang = :yaml
            when 'css'
                lang = :css
            when 'html'
                lang = :html
            when ''
                lang = :md
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(
          filter_html: true,
          hard_wrap: true,
          link_attributes: { rel: 'nofollow', target: "_blank" }
        )
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    options = {
      hard_wrap:       true,
      space_after_headers: true,
    }

    extensions = {
      autolink:           true,
      no_intra_emphasis:  true,
      fenced_code_blocks: true,
    }

    unless @markdown
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end

    @markdown.render(text).html_safe
  end
end

app/views/texts/_text.html.erb
<% if @watched_texts_id.include?(text.id) %>
  <%= render partial: "texts/watched", locals: { text: text} %>
<% else %>
  <%= render partial: "texts/unwatched", locals: { text: text} %>
<% end %>

app/views/texts/_unwatched.html.erb
<%= link_to "読破済みにする", text_watched_texts_path(text) ,method: :post, remote: true, class:"btn unwatched" %>

app/views/texts/_watched.html.erb
<%= link_to "読破済みを解除", text_watched_texts_path(text) ,method: :delete, remote: true, class:"btn watched" %>

app/views/texts/index.html.erb
<div class="text">
  <h3 class="text-center">テキスト教材</h3>
  <div class="input-group justify-content-center">

    <input type="text" id="search-text" placeholder="教材を探す" style="width:30%;">

    <span class="input-group-btn">
      <button type="button" class="btn btn-default"></button>
    </span>
  </div>
</div>


<div class="text-content">
    <div class="container-fluid">
      <div class="row">
          <% @texts.each do |text| %>
         <div class="col-md-4 d-flex" id="text">
            <div class="card">
              <%= image_tag text.image_url(:thumb) ,class:"card-img" %>
              <div class="card-body">

                <div id="watched_text_<%= text.id %>" class="text_button" >
                  <%= render partial: "texts/text", locals: { text: text} %>
                </div>

                <h4 class="card-title"><%= "#{text.title}" %></h4>
                <p class="card-text"><%= "【#{text.genre}】" %></p>
              </div>
            </div>
         </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/texts/show.html.erb
<div class="text-show">
  <div class="text-title">
    <%= markdown(@text.title).html_safe %>
  </div>
  <%= markdown(@text.content).html_safe %>
</div>